apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: alexg25/online_inference_mlops:v2
      name: online-inference
      ports:
        - containerPort: 7000
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "300m"
      readinessProbe:
        httpGet:
          path: /status
          port: 7000
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /status
          port: 7000
        initialDelaySeconds: 60
        periodSeconds: 10