apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
      - name: online-inference
        image: alexg25/online_inference_mlops:latest
        ports:
          - containerPort: 7000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "300m"