# @package _group_
numerical_features:
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"
  - "oldpeak"
categorical_features:
  - "sex"
  - "cp"
  - "fbs"
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
features_to_drop: []
target_col: "condition"